### ISSUE TITLE
Navigate to the line in the code where the call is made, instead of to the method definition

### ISSUE THREAD

**Issue by thermopyle** [dolmens/eglot-hierarchy#2]
Thanks for a great package!

I have a suggestion, or a request rather; when selecting a node in the hierarchy to navigate to the call site, instead of ending up at the declaration of the calling function, it would be preferable to navigate to the specific line where the call is made, within the calling function.

I do not know if this information is present or how hard it would be. And I regret not being able to help with a pull request, my knowledge of ELisp is far too bad.

**Comment by dolmens** [comment]
It's doable, at least in some LSPs, I will be on it soon.

**Comment by dolmens** [comment]
Custom variable `eglot-hierarchy-call-site` was added, if set to t, then clicking the hierarchy item will navigate to the **first** call site instead of the function start.

**Comment by wiktor-k** [comment]
I've tested and it works. I think this ticket can be closed.

Btw, this is an excellent plugin and thank you *very much* for it. :bow: 

Is there a reason it's not available on MELPA? (it's not a big problem but this way it'd reach more folks)

**Comment by dolmens** [comment]
> Is there a reason it's not available on MELPA? (it's not a big problem but this way it'd reach more folks)
I just don’t think too many people really need it.
